### ISSUE TITLE
Doesn't process keyword "include"

### ISSUE THREAD

**Issue by erosh** [Juniper/open-register-design-tool#12]
Hi.
Your open-register-design-tool is very cool.
But using it I faced an issue. It can't parse includes. 

addrmap top
{
        \`include   "app.rdl"
	\`include   "pf.rdl"

    app         app               @0x0000;
    pf          pf                @0x0100;	
};

It is possible to add "Include" processing?

And I noticed that '\n' character is not allowed. Why?
And if I want to add symbol " inside a string - like \" - it is ignored

Thanks

**Comment by sdnellen** [comment]
File includes would be handled by a preprocessor - see https://github.com/Juniper/open-register-design-tool/wiki/Running-Ordt#input-file-pre-processors (and also issue #10).
Rdl string define doesn't support these escaped symbol characters.  Can use cr in a description string w/o the escape n such as

       	            desc="Sets a port number that is assigned to any req that is
	            converted to a local grant.";

and the return will be carried into outputs using the string.

**Comment by erosh** [comment]
Thanks
