### ISSUE TITLE
Feature request: print `uvm_object_utils statement at the end of register class

### ISSUE THREAD

**Issue by paulthilking** [Juniper/open-register-design-tool#16]
This feature is useful for users of the register model that want to extend a register description with randomization constraints, and then use the new class from the factory.

Looks like it just requires a one line fix at the end of buildRegClass.

**Comment by paulthilking** [comment]
Also requires the use of create() instead of new() for the reg items.

**Comment by sdnellen** [comment]
Added **regs_use_factory** boolean uvmregs parameter in 170727.01 - set true to add utils/create for regs.  We had removed factory on regs as it has some performance impact (false is still default).

**Comment by sdnellen** [comment]
feature is in 170915.01.
