### ISSUE TITLE
 Feature Request: extend 'hw' processing

### ISSUE THREAD

**Issue by erosh** [Juniper/open-register-design-tool#20]
I would be great if we can distinct all 'hw' values.
For now converter to xml ignores hw = na; and hw = r; 
and for both hw = w and hw = rw it creates empty tag <hwmod>

**Comment by sdnellen** [comment]
What version are you running?  As of 170727.01, this info would be in the hwaccess tag in the xml output.

**Comment by erosh** [comment]
Great. I had 170714.01
