### ISSUE TITLE
enumerate information is missing in generated XML

### ISSUE THREAD

**Issue by zhangpengsjtu** [Juniper/open-register-design-tool#30]
I have below enum and field defined in my systemRDL file, but after I run ORDT, I found that there is no enum information in the output xml file. 

May I know any option to get the enum dumped in output XML file, or it is not supported?

For example 
        enum ERRSLICE0_MISSIONERR_ENABLE_ERR25_enum{
           DISABLE = 1'd0;
           ENABLE = 1'd1;
        };
        field {encode=ERRSLICE0_MISSIONERR_ENABLE_ERR25_enum;sw=rw;hw=r;reset=1'h1;} ERR25[25:25];

**Comment by sdnellen** [comment]
updated to add enum info to xml output in v171023.02.  will be picked up in next release.

**Comment by zhangpengsjtu** [comment]
May I know when will be the next release, as we are going to use ORDT in one of our active open source projects

**Comment by sdnellen** [comment]
Probably next week - you can always create a jar from latest source though.

**Comment by zhangpengsjtu** [comment]
Thanks, I will watch ordt, and wait for the next release
