### ISSUE TITLE
ExtParameters.java has ^M characters at the end of each line

### ISSUE THREAD

**Issue by paulthilking** [Juniper/open-register-design-tool#32]
I see the ^M chars after a pull to a linux system. I don't see this in any other files, so I assume it was introduced in a recent commit.

**Comment by sdnellen** [comment]
That's strange - committing from same mac, so not sure why this one is difft.  I recommitted the file, but if still seeing this, you may want to try setting 'git config --global core.autocrlf input' and see if this cleans up in linux pull.

**Comment by paulthilking** [comment]
The file contents look ok now, no git config required.
