### ISSUE TITLE
Feature Request: Function to get register name

### ISSUE THREAD

**Issue by kprabhu36** [Juniper/open-register-design-tool#51]
It will be good to have a function to get register name by passing address/tag similar to get_address.  

I hope this should have been implemented already since -reglist option dumps the complete register/field names.

**Comment by sdnellen** [comment]
Not sure what you are looking for, but the c++ driver model would not be the place for this - its basic function is to convert a register path to an address.   Please provide more info on this request and how/why it would be used.

**Comment by kprabhu36** [comment]
We have a requirement to get the register name (complete the hierarchy name) using the address.

**Comment by sdnellen** [comment]
Python model added in 181009.01 includes a get_address method.  Still tbd in C++ model.

**Comment by sdnellen** [comment]
I am closing this issue since get_path (from address) method is now available in python model output.  Available in release 190524.01.
