### ISSUE TITLE
Default bit ordering on reg fields

### ISSUE THREAD

**Issue by natcoro** [Juniper/open-register-design-tool#53]
Question: When writing a register where I only specify the bits of one field (fieldthree [5:4]), once it is generated I can see on the XML file that the bit positioning of the register fields is not on a lsb0 order. (Fieldtwo is at bit 1, fieldthree is at bit 5:4  and fieldfour goes to bit 2). Is the bit ordering supported in this case? 
Ex:
 reg example_t {
        name = "example register";
        desc = "register to test field order";
            default hw = r;
            default sw = rw;
        field {
            hw = r;
            sw = rw;
        } fieldone;
        field {
            hw = r;
            sw = rw;
        } fieldtwo;
        field {
            hw = r;
            sw = rw;
        } fieldthree[5:4];
        field {
            hw = r;
            sw = rw;
        } fieldfour;
Output:
`-<field>`
`<id>**fieldtwo**</id>`
`<access>RW</access>`
`-<hwinfo>`
`<hwaccess>r</hwaccess>`
`</hwinfo>`
`**<lowidx>1</lowidx>**`
`<width>1</width>`
`</field>`
`-<field>`
`<id>**fieldthree**</id>`
`<access>RW</access>`
`-<hwinfo>`
`<hwaccess>r</hwaccess>`
`</hwinfo>`
`**<lowidx>4</lowidx>`
`<width>2</width>**`
`</field>`
`-<field>`
`<id>**fieldfour**</id>`
`<access>RW</access>`
`-<hwinfo>`
`<hwaccess>r</hwaccess>`
`</hwinfo>`
`**<lowidx>2</lowidx>**`
`<width>1</width>`
`</field>`

**Comment by sdnellen** [comment]
If no bit location is specified for a field, it will be placed at the first available location starting at lsb0.  In the case above, this is index 2 for fieldfour.  To force this field to a specific location, use eg...

    field { hw = r; sw = rw; } fieldfour[6:6];

**Comment by natcoro** [comment]
Thank you
