### ISSUE TITLE
how to write addrmap block?

### ISSUE THREAD

**Issue by zhajio1988** [Juniper/open-register-design-tool#72]
- below is my addrmap block look likes:

*** ERROR ***: No rdl structures instanced or typedefs specified for processing.
`
addrmap addrmap_PICO{
    name = "ATXMEGA SPI controller";
    desc = "Register description of Atmel XMEGA AU's SPI controller
    Transcribed from original manual as an example exercise:
    http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-8331-8-and-16-bit-AVR-Microcontroller-XMEGA-AU_Manual.pdf";
    signal { activelow; field_reset; cpuif_reset;} reset_n;
    regs_ral_demo ral_regs_demo @0x0;
};
`

- below writing method will give warning:

_*** WARNING ***: More than one root instance found in input file. Only first instance (a) will be processed._

`
addrmap addrmap_PICO{
    name = "ATXMEGA SPI controller";
    desc = "Register description of Atmel XMEGA AU's SPI controller
    Transcribed from original manual as an example exercise:
    http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-8331-8-and-16-bit-AVR-Microcontroller-XMEGA-AU_Manual.pdf";
    signal { activelow; field_reset; cpuif_reset;} reset_n;
    regs_ral_demo ral_regs_demo @0x0;
} a;
`
- below writing method will give  error and warning:
*** ERROR ***: Duplicate instance (addrmap_PICO) declared in component root
*** WARNING ***: More than one root instance found in input file. Only first instance (addrmap_PICO) will be processed.

`
addrmap addrmap_PICO{
    name = "ATXMEGA SPI controller";
    desc = "Register description of Atmel XMEGA AU's SPI controller
    Transcribed from original manual as an example exercise:
    http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-8331-8-and-16-bit-AVR-Microcontroller-XMEGA-AU_Manual.pdf";
    signal { activelow; field_reset; cpuif_reset;} reset_n;
    regs_ral_demo ral_regs_demo @0x0;
} addrmap_PICO;
`
main difference is addrmap name position.

**Comment by sdnellen** [comment]
ordt looks for a single addrmap instance at root level by default - if multiple components are instanced at root, only the first will be processed.  Format of an rdl addrmap component is...

      addrmap <optional_component_name> {
           …addrmap .contents
      } <optional_instance_name> ;

So, you could do either....

      addrmap  {
           …addrmap .contents
      } addrmap_PICO_instance_name  ;

Or....

      addrmap  addrmap_PICO {
           …addrmap .contents
      } ;
      addrmap_PICO addrmap_PICO_instance_name;

See the wiki for details/examples.

**Comment by zhajio1988** [comment]
> ordt looks for a single addrmap instance at root level by default - if multiple components are instanced at root, only the first will be processed. Format of an rdl addrmap component is...
> 
> ```
>   addrmap <optional_component_name> {
>        …addrmap .contents
>   } <optional_instance_name> ;
> ```
> 
> So, you could do either....
> 
> ```
>   addrmap  {
>        …addrmap .contents
>   } addrmap_PICO_instance_name  ;
> ```
> 
> Or....
> 
> ```
>   addrmap  addrmap_PICO {
>        …addrmap .contents
>   } ;
>   addrmap_PICO addrmap_PICO_instance_name;
> ```
> 
> See the wiki for details/examples.

@sdnellen  so 
`
addrmap addrmap_PICO{ name = "ATXMEGA SPI controller"; desc = "Register description of Atmel XMEGA AU's SPI controller Transcribed from original manual as an example exercise: http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-8331-8-and-16-bit-AVR-Microcontroller-XMEGA-AU_Manual.pdf"; signal { activelow; field_reset; cpuif_reset;} reset_n; regs_ral_demo ral_regs_demo @0x0; };
`
is wrong usage?

**Comment by sdnellen** [comment]
The usage isn't incorrect, but it doesn't tell the tool what to run - keep in mind multiple addrmap components can be defined at root level and for some outputs, having no addrmap is a valid form.  The first root instance tells the tool what to run by default.  Alternately, an rdl input control parameter can be specified to process a specific component, eg *process_component = "addrmap_PICO"*.

**Comment by zhajio1988** [comment]
@sdnellen 
thank you . i understand.
