### ISSUE TITLE
"gated_logic_access_delay" affects access delay even if clock gating disabled

### ISSUE THREAD

**Issue by roowatt** [Juniper/open-register-design-tool#74]
After some testing with the latest release I notice that there is a significant access delay, looking into the options I found the "gated_logic_access_delay" setting that impacted it, even when clock gating is disabled.

What is the expected access delay with the parallel option and clock gating disabled? 

What is the minimum I should be able achieve? How to configure for that?

**Comment by sdnellen** [comment]
Unable to reproduce this issue.  With parallel interface and no **use_gated_logic_clock** or **gated_logic_access_delay** parameters specified, a delay of 2 cycles is observed between *pio_dec_read/write* and *dec_pio_ack* response when accessing an internal register in the root decoder (this is the min delay - see waves below).  If only the **gated_logic_access_delay** is specified, no change in behavior is observed.  If **use_gated_logic_clock** is specified as true, the *dec_pio_ack* will be delayed by an additional **gated_logic_access_delay** cycles. 

![simple_r_w](https://user-images.githubusercontent.com/433721/64068929-90f30e80-cc0d-11e9-978e-3dea19c36d01.PNG)

**Comment by roowatt** [comment]
Thanks for looking into it, it looks like a problem in my build system.
